### ISSUE TITLE
private key location - README does not match the PE docs

### ISSUE THREAD

**Issue by robbyt** [puppetlabs/control-repo#14]
The docs for this repo say to place the private key at:

> /etc/puppetlabs/puppetserver/code_manager.key

And the PE docs at https://docs.puppetlabs.com/pe/latest/cmgmt_control_repo.html say this:

> After PE installation is complete, place this private key in a location that the pe-puppet user can access; we recommend /etc/puppetlabs/puppetserver/ssh/id-control_repo.rsa. The file itself should have the correct permissions for the pe-puppet user, which is created during PE installation, to use that key.

**Comment by npwalker** [comment]
@robbyt The location of the key and it's name doesn't matter for functionality but I assume you are simply pointing out that this is inconsistent.  

I would say it doesn't matter but I do appreciate the clarity of having an ssh directory under the puppetserver directory instead of just placing the key in the puppetserver directory like I did.  

If I change the name/location of the key I'll need to remove the old private and public key as well as check the behavior of the git_deploy_key to make sure it correctly replaces the existing deploy key instead of creating a new deploy key and leaving the old one around.

**Comment by robbyt** [comment]
@npwalker I understand that the location is configurable. Just pointing out the inconsistency between the two documentation sources. We just want to know the one "true way" to configure code-manager :)

**Comment by npwalker** [comment]
@robbyt this should be resolved by the merge of https://github.com/puppetlabs/control-repo/pull/22
