### ISSUE TITLE
r10k postrun not running

### ISSUE THREAD

**Issue by cbowlesut** [puppetlabs/control-repo#16]
@npwalker  

I am using a slightly modified version of your control-repo, but for some reason my postrun commands are not running, so my Puppet Enterprise console environments are never being updated.   

Could you validate if your test rigs are correctly running the postrun commands configured in hiera?

**Comment by npwalker** [comment]
@cbowlesut are you using code manager in 2015.3 or r10k in 2015.2?  

In 2015.3 code manager does not support a post_run command so that hiera key doesn't do anything but is there for compatibility with 2015.2.  

In 2015.3 I'd suggest you use the refresh classes button to get a refreshed class list instead of a full browser refresh.  

If you do not prefer that then you can always set the $force_zack_r10k_webhook parameter and continue to use r10k.  

https://github.com/puppetlabs/control-repo/blob/production/site/profile/manifests/git_webhook.pp#L2

Let me know what you think.

**Comment by cbowlesut** [comment]
@npwalker 
Code Manager in 2015.3.  That totally makes sense.

Will use the default environment settings and "refresh class" button as needed.

Thanks for the quick reply!
