### ISSUE TITLE
Where should i put my custom facts

### ISSUE THREAD

**Issue by shishirsharma** [puppetlabs/control-repo#42]
Where (which directory) should i put my custom facts. I am using r10k for deployment.

**Comment by pizzaops** [comment]
Hi @shishirsharma - this isn't really the right place to ask for support, since this is for bugs, feature requests, etc.

That said, custom facts can be stored in the `lib` directory of any module.

If the facts are not related to one specific module, I often put them in the `lib` directory of a module called `custom`.

If the facts are related to one specific module, e.g. you wrote a mysql module and wrote some facts to collect information about mysql, then put them in the `lib` directory of that module.

If they are related to a module, but that module is a Forge module, then use the `custom` module as I mentioned, since putting them directly into the Forge module would be essentially forking the module.

Hope that helps! If you have other questions, check out #puppet on Freenode or puppetcommunity.slack.com!
